### ISSUE TITLE
remakeConstraints broken

### ISSUE THREAD

**Issue by krzd** [Masonry/Snap#40]
remakeConstraints does not behave correctly since cf977c5a1a624c5f433132bcd4f344497eb1db9b or 0b92c7ff5426b4e87196214b6de4bf831dad9ca3. I cannot really tell because the former does not compile.
I cannot really understand what goes wrong, but some constraints don't seem to be applied correctly. If it makes any difference for those views I only used remakeConstraint and not makeConstraints for the first time.
Please let me know if I can provide you with anything to help resolve this issue.

**Comment by robertjpayne** [comment]
@krzd thanks for this. I think I made some poor choices around how the constraints were stored for remaking etc… I've just pushed Cocoapods v0.0.4 up if you want to give it a go it should fix this.

If it doesn't open a new issue please!
