### ISSUE TITLE
need ios8?

### ISSUE THREAD

**Issue by babyfamily** [Masonry/Snap#42]
:(

**Comment by devxoul** [comment]
See #41 and https://github.com/Masonry/Snap/commit/d9fdc78bfbf22722c94cd0d7c6c126964c7190f1 for more information.

**Comment by robertjpayne** [comment]
Yea unfortunately I'm forcing iOS 8.0 on the Podspec. It's pretty easy to integrate yourself for iOS 7.0 but I'm not going to support it in the Podspec unless Cocoapods ever has support just to avoid a headache.
