### ISSUE TITLE
Use of undeclared type Constraint

### ISSUE THREAD

**Issue by JohnnyRuvac** [Masonry/Snap#48]
Hey guys,

I'm not sure If I just made mistake in integration of Snap in my project, but I get this error when I try to create property of type constraint in one of my classes.
I use snap on other places and it works well, but now I need to reference particular constraint. Any ideas what might be wrong?
I followed instructions for integrating snap in read me of this repository.

Thanks for help.

**Comment by JohnnyRuvac** [comment]
I tried one more thing, but unfortunately still have the same issue.
I removed Snap as submodule, and tried adding it with pre-release version of Cocoapods instead.

**Comment by robertjpayne** [comment]
@JohnnyRuvac can you post some sample code? Not really sure I follow what you're doing.

**Comment by JohnnyRuvac** [comment]
Hi, I found what was the problem. I forgot to import Snap in class where I wanted to use it. 
Actually, I didn't know that you have to import it. Maybe it might be nice to mention it in read me somewhere? Because I thought that using swift, you don't have to import manually, everything is already there. This is clearly exception, because it is external framework? It is also a bit weird for me, that snp_makeConstraints was working on UIView without importing snap.

For clarity, here is link to a gist: https://gist.github.com/JohnnyRuvac/51e644da3f3bd65dbda2
