### ISSUE TITLE
make versus maker

### ISSUE THREAD

**Issue by iwasrobbed** [Masonry/Snap#52]
In the README, the examples are listed a bit differently than how the swift files are implemented:

```swift
public func snp_makeConstraints(block: (maker: ConstraintMaker) -> ()) {
  ConstraintMaker.makeConstraints(self, block: block)
}
```

so essentially would give `maker` which reads a bit strangely versus `make`:

```swift
self.openCameraButton.snp_makeConstraints { (maker) -> () in
  maker.bottom.equalTo(self.view.snp_bottom)
  maker.left.equalTo(self.view.snp_left)
  maker.right.equalTo(self.view.snp_right)
  maker.height.equalTo(75)
}
```

versus the example (and prior Masonry implementation) of:

```swift
view1.snp_makeConstraints { make in
  make.top.equalTo(superview.snp_top).with.offset(padding.top) // with is an optional semantic filler
  make.left.equalTo(superview.snp_left).with.offset(padding.left)
  make.bottom.equalTo(superview.snp_bottom).with.offset(-padding.bottom)
  make.right.equalTo(superview.snp_right).with.offset(-padding.right)
}
```

I just wanted to get clarification around which approach you'll be taking.

**Comment by JohnnyRuvac** [comment]
I think that you should install code snippets, it is mentioned at the bottom of the read me. Then you should be able to use make instead of maker.

**Comment by cloudkite** [comment]
+1 I think we should rename the parameter to make.

@robertjpayne what do you think?

**Comment by robertjpayne** [comment]
OH YES I really need to do this @cloudkite @JohnnyRuvac sorry it's on my list.. so annoying

**Comment by robertjpayne** [comment]
@cloudkite @JohnnyRuvac this is done! and pushed as Snap 0.0.6
