### ISSUE TITLE
Swift Compiler Warning

### ISSUE THREAD

**Issue by ryanmaxwell** [Masonry/Snap#53]
Another thing to investigate when the time comes! 

"Umbrella header for module 'Snap' does not include header 'Snap-Swift.h'
![screen shot 2015-02-11 at 09 23 01](https://cloud.githubusercontent.com/assets/718440/6135732/ce1c6a84-b1cf-11e4-937e-0d0cce01abee.png)

**Comment by ryanmaxwell** [comment]
I think this may be an issue by the umbrella header auto generated by a cocoapod install

**Comment by skrinko** [comment]
I've had this issue with other cocoapods.  Adding it as a submodule works perfect.

**Comment by robertjpayne** [comment]
@ryanmaxwell is this related to Swift 1.2?

**Comment by ryanmaxwell** [comment]
@robertjpayne Yesterday involved me both updating from cocoapods 0.36 beta 1 to beta 2, as well as updating to swift 1.2 and xcode 6.3 beta. So it's one of those! But my hunch is it's a cocoapods fault, as the umbrella header they talk about is generated by cocoapods. Maybe there is an extra flag that needs to be activated for swift-objc compatibility headers?

**Comment by robertjpayne** [comment]
@ryanmaxwell I'm running 0.36 beta 2 without issues but I'll double check right now!

**Comment by robertjpayne** [comment]
@ryanmaxwell no issues here, hrm I'm going to bank on Xcode 6.3 beta.

**Comment by Reflejo** [comment]
I haven't seen this neither and I'm using Xcode 6.3 beta. Have you tried to remove derivateddata an clean the project?.
