### ISSUE TITLE
Question: proportional width / height

### ISSUE THREAD

**Issue by mkoppanen** [Masonry/Snap#54]
Hello,

I might be overlooking something but cant figure out how to do proportional width / height constraints. I.e. view1 height is 50% of view2 height. Is this supported by Snap?

**Comment by devxoul** [comment]
Of course, you can use `dividedBy` or `multipliedBy`.

```swift
view1.snp_makeConstraints { make in
    make.height.equalTo(view2).dividedBy(0.5)
}
```

**Comment by mkoppanen** [comment]
Excellent! Thanks!

**Comment by devxoul** [comment]
Glad it helped :)
