### ISSUE TITLE
Facebook POP animation

### ISSUE THREAD

**Issue by at--world** [Masonry/Snap#57]
Is there a way to do an animation with the POP framework and snap like https://github.com/miklselsoe/MSSPopMasonry ?

**Comment by robertjpayne** [comment]
@at--world these questions are best for Stackoverflow. It would be possible but you'd need to replicate the class categories provided by that repository.

**Comment by wxxsw** [comment]
https://github.com/wxxsw/POP-Snap

**Comment by itaydressler** [comment]
@wxxsw Thanks!
