### ISSUE TITLE
Xcode 6.3 (Swift 1.2 beta 2) crash

### ISSUE THREAD

**Issue by ryanmaxwell** [Masonry/Snap#59]
Don't shoot the messenger!

![screen shot 2015-02-24 at 14 41 50](https://cloud.githubusercontent.com/assets/718440/6341763/4f234086-bc33-11e4-978d-f04cd057be28.png)

**Comment by ryanmaxwell** [comment]
This commit by @Reflejo sorts it, but it's a workaround https://github.com/Reflejo/Snap/commit/ce31f2c29319271ac93bb83da4ba34b44b707401

**Comment by robertjpayne** [comment]
@ryanmaxwell thanks, is this on the swift-1.2 branch?

**Comment by ryanmaxwell** [comment]
@robertjpayne yep

**Comment by robertjpayne** [comment]
I'll be looking into Swift 1.2 late next week! Will tidy this up and anything else.

**Comment by ryanmaxwell** [comment]
@robertjpayne may be a 6.3 beta 3 out next week based on the timing between beta 1 and 2

**Comment by robertjpayne** [comment]
@ryanmaxwell one quick question – was this on a debug or release build?

**Comment by ryanmaxwell** [comment]
@robertjpayne it was on debug. It doesn't crash anymore for me on beta 3, using the head of the swift-1.2 branch.

**Comment by robertjpayne** [comment]
You reckon it's safe for me to delete this issue than @ryanmaxwell? Seems like it was more just a Swift issue rather than a Snap issue?

**Comment by robertjpayne** [comment]
Also because of that I don't think we have any specific Swift 1.2 stuff, I can probably delete the branch and just continue with develop/master

**Comment by ryanmaxwell** [comment]
Yep
