### ISSUE TITLE
Snap does not support platform iOS 7.0

### ISSUE THREAD

**Issue by jerry-sl** [Masonry/Snap#61]
I recently add Snap to my Swift project following README. But got error:  [!] The platform of the target `Pods` (iOS 7.0) is not compatible with `Snap (0.0.6)` which has a minimum requirement of iOS 8.0 - OS X 10.9.

My pod version is 0.36.0. Is this a bug or README Requirements section is outdated?

**Comment by phamquochoan** [comment]
Cocoapods and Carthage only support ios 8.0 and above.
You have to install Snap manually.

**Comment by jerry-sl** [comment]
@phamquochoan  thx. I will try manually install.
