### ISSUE TITLE
CocoaPods fails with Snap 0.9.1

### ISSUE THREAD

**Issue by CWalig** [Masonry/Snap#62]
Hey,

I just tried to install Snap via CocoaPods but I keep getting this error....
I tried with the default Podfile provided in the README.md

```
[!] Unable to satisfy the following requirements:

- `Snap (~> 0.9.1)` required by `Podfile`
```

I also tried to use the develop branch, Snap is installed but the Snap folder in the pod is empty....

So for the moment I did roll back to 0.0.9

any ideas ? 

Thanks !

**Comment by imWildCat** [comment]
Currently the latest version of Snap in CocoaPods in 0.9.0

http://cocoapods.org/?q=Snap

Replace `Snap (~> 0.9.1)` by `Snap (~> 0.9.0)`

**Comment by CWalig** [comment]
👍
