### ISSUE TITLE
snapkit.io link of About section is not working

### ISSUE THREAD

**Issue by anubhavpulkit** [Masonry/Snap#751]
### New Issue Checklist

* [X] I have looked at the [Documentation](http://snapkit.io/docs)
* [X] I have read the [F.A.Q.](http://snapkit.io/faq)
* [X] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | e.g. carthage/cocoapods/manually
 

### Issue Description

The link of snapkit.io (http://snapkit.io/) is not working.

**Comment by robertjpayne** [comment]
Ah crap, I'll sort this out.

**Comment by robertjpayne** [comment]
I've updated the links on the repo to just point to github pages.
