### ISSUE TITLE
snapkit.io has become a spam site

### ISSUE THREAD

**Issue by aydenp** [Masonry/Snap#765]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [X] I have looked at the [Documentation](http://snapkit.io/docs)
* [X] I have read the [F.A.Q.](http://snapkit.io/faq)
* [X] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | N/A
 Platform Version        | N/A
 SnapKit Version         | N/A
 Integration Method      | N/A
 

### Issue Description

SnapKit[.]io, linked in the about section, is a spam gambling site.

<img width="347" alt="image" src="https://user-images.githubusercontent.com/23015217/204285879-5d1334d8-6a2a-49a3-ba0e-277aa4fadb36.png">

<img width="1531" alt="image" src="https://user-images.githubusercontent.com/23015217/204285944-a9e3fbbd-bbdb-455d-8ce9-257185bc87eb.png">

**Comment by aydenp** [comment]
<img width="347" alt="image" src="https://user-images.githubusercontent.com/23015217/204285879-5d1334d8-6a2a-49a3-ba0e-277aa4fadb36.png">

**Comment by aydenp** [comment]
I see #751 as well, looks like someone has bought it to take it over with spam as above

**Comment by robertjpayne** [comment]
I've updated the links on the repo to just point to github pages.
