### ISSUE TITLE
About new changes

### ISSUE THREAD

**Issue by Reflejo** [Masonry/Snap#77]
I saw that you removed `and` and `with` as well as created a new `ConstraintDescriptionExtendable` class.

My question is: before this was allowed:

```swift
view.snp_updateConstraints { make in
    make.top.offset(tableFooterY)
}
```

How are you planning to support updating a constraint like this?

**Comment by Reflejo** [comment]
I guess it was a stupid question: The right way would be to create the full constraint as
```make.equalTo(whatever).offset(tableFooterY)```

**Comment by robertjpayne** [comment]
@Reflejo 
Or you can just do make.equalTo(tableFooterY)

**Comment by Reflejo** [comment]
Won't that change the logic? I didn't show you the complete example:

First:
```swift
view.snp_updateConstraints { make in
    make.top.equalTo(view).offset(tableFooterY)
}
```

... Later on ...
```swift
view.snp_updateConstraints { make in
    make.top.offset(tableFooterY)
}
```

So the idea is to keep the relation to `view` but just change the offset

**Comment by robertjpayne** [comment]
@Reflejo 

Pretty sure these are all identical assuming `view.snp_makeConstraints`

`make.top.equalTo(50)`
`make.top.equalTo(view).offset(50)`
`make.top.equalTo(view.superview!).offset(50)`

**Comment by Reflejo** [comment]
Yeah sorry I updated my code, the idea was that the relation of `view` is to `someOtherView`. Not to itself

**Comment by robertjpayne** [comment]
If you're constraining a location attribute ( top, left, right etc… ) and use a constant in the `equalTo` portion of the constraint it will always constrain to the view's superview.

If you're constraining a dimension attribute ( width, height ) and use a constant in the `equalTo` portion of the constraint it will always constrain to the view itself.

**Comment by Reflejo** [comment]
:+1: closing this

**Comment by robertjpayne** [comment]
@Reflejo I also encourage people to take advantage of the new updating functions on built constraints:

```
var constraint: Constraint? = nil
view.snp_makeConstraints { make in
    constraint = make.top.equalTo(50).constraint
}
constraint.updateOffset(100)
```
