### ISSUE TITLE
Couldn't checkout revision error with Swift Package Manager

### ISSUE THREAD

**Issue by denproz** [Masonry/Snap#771]
### New Issue Checklist

*  ✅ I have looked at the [Documentation](http://snapkit.io/docs)
* ✅ I have read the [F.A.Q.](http://snapkit.io/faq)
* ✅ I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | Xcode 14.3, iOS 16.4
 SnapKit Version         | 5.6.0
 Integration Method      | SPM
 

### Issue Description

Seems like SPM cannot fetch the version of SnapKit, 5.6.0 (and any below, starting from 5.0.1) fail with the following error:

<img width="663" alt="Screenshot 2023-05-12 at 15 53 43" src="https://github.com/SnapKit/SnapKit/assets/59484569/785b8a9e-7938-431f-9795-8f1df1ddb8b3">

**Comment by robertjpayne** [comment]
This still an issue for you? Seems odd -- nothing SnapKit does is really part of the way Swift PM works

**Comment by denproz** [comment]
> 

Yes, still is

**Comment by denproz** [comment]
Yes, it still is
