### ISSUE TITLE
Low version adaptation problem (12.5.7)

### ISSUE THREAD

**Issue by langyangyangzzZ** [Masonry/Snap#772]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [T] I have looked at the [Documentation](http://snapkit.io/docs)
* [T] I have read the [F.A.Q.](http://snapkit.io/faq)
* [T] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | iPhone 12.5.7
 SnapKit Version         | 5.6.0
 Integration Method      |manually
 

## Issue Description
I'm a new ios developer. The same piece of code runs differently on 12.5.7 and 16.4.1. I am using the snapKit framework for UITableView custom Cell height, in 12.5.7, make.bottom will not work, please help me, thank you

## code:
![image](https://github.com/SnapKit/SnapKit/assets/54341625/3933fcaf-c051-428e-b8d7-a54c3c0a7218)

## operation result
![image](https://github.com/SnapKit/SnapKit/assets/54341625/94745578-0c30-4302-8a8f-a9ad1f52884d)

**Comment by MichaelPei** [comment]
Actually, you shouldn't try to add constraint on contentView of a UITableViewCell
In your case, just remove all the constraints set for contentView, add one constraint for  tvLabel for the bottom should be OK.

**Comment by langyangyangzzZ** [comment]
> 

ohhh!! Indeed it is, thank you.

**Comment by langyangyangzzZ** [comment]
I would like to know why the low version setting contentView interface will disappear? But the high version will not

**Comment by MichaelPei** [comment]
Actually SnapKit is like a translator to translate your constraints to iOS native constraints, so in your scenario, the delta should be the iOS system underlying constraints logic change, not related to SnapKit.
So basically if you do something wrong, maybe system may behave right in some versions and wrong in future versions, the reason should not be so important.
