### ISSUE TITLE
Apple Vision Pro: No such module 'AppKit'

### ISSUE THREAD

**Issue by JoshuaSullivan** [Masonry/Snap#778]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [ X ] I have looked at the [Documentation](http://snapkit.io/docs)
* [ X ] I have read the [F.A.Q.](http://snapkit.io/faq)
* [ X ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | visionOS
 Platform Version        | 1.0
 SnapKit Version         | 5.6.0
 Integration Method      | Swift Package Manager
 

### Issue Description

When attempting to migrate our iOS app to visionOS in Xcode 15.0 b7, the SnapKit framework fails to compile due to the following code in Constraint.swift:

```
#if os(iOS) || os(tvOS)
    import UIKit
#else
    import AppKit
#endif
```

This compiler directive needs to be modified to include a condition for visionOS.

**Comment by Liaoworking** [comment]
same issue here.

**Comment by robertjpayne** [comment]
I've merged a PR for this I'll cut a release probably late next week

**Comment by drewolbrich** [comment]
> I've merged a PR for this I'll cut a release probably late next week

Thank you.
