### ISSUE TITLE
Would it be possible to have a new release?

### ISSUE THREAD

**Issue by CraigSiemens** [Masonry/Snap#785]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 17
 SnapKit Version         | 5.6.0
 Integration Method      | carthage
 

### Issue Description

It looks like it's been over a year since the last release but there's some PRs since then that'd  be nice to have in an official release. The main one I'd like is https://github.com/SnapKit/SnapKit/pull/750 since it's caused some issues in our app where people used `greaterThanOrEqualTo(...)` assuming it created a constraint to self instead of superview.

Also, the links in the issue template 404.

**Comment by wlxo0401** [comment]
Check out the new releases.

**Comment by robertjpayne** [comment]
5.7.1 is available now on both SPM and Cocoapods 🥳

**Comment by wlxo0401** [comment]
@robertjpayne Thank you for your continuous care.
