### ISSUE TITLE
privacy manifest

### ISSUE THREAD

**Issue by cashleeboy** [Masonry/Snap#786]
This repo needs to provide a privacy manifest, as described here: https://developer.apple.com/news/?id=av1nevon, thank a lot.

**Comment by infinitepower18** [comment]
This package has been explicitly mentioned by Apple as one of the packages that must include a manifest. https://developer.apple.com/support/third-party-SDK-requirements

**Comment by wlxo0401** [comment]
Snapkit, come back to life.

**Comment by zeroskylian** [comment]
+1

**Comment by isaac-weisberg** [comment]
Someone should just do it, it's easy peasy

**Comment by wlxo0401** [comment]
@isaac-weisberg 

Is it possible for someone to ascertain whether any of Apple's listed APIs were used even if they weren't directly involved in the development?

And I understand that snapkits should also be signed.

**Comment by lambda123254** [comment]
+1

**Comment by ZYHshao** [comment]
+1

**Comment by 18320537910** [comment]
+1

**Comment by wlxo0401** [comment]
I submitted one [PR](https://github.com/SnapKit/SnapKit/pull/793) for 'Privacy Manifest'. But I'm not sure. 

Let's check together, find problems, improve them together and try to get into a new version.

@zeroskylian @cashleeboy @infinitepower18 @isaac-weisberg @lambda123254 @ZYHshao @18320537910

**Comment by zeroskylian** [comment]
> I submitted one [PR](https://github.com/SnapKit/SnapKit/pull/793) for 'Privacy Manifest'. But I'm not sure.
> 
> Let's check together, find problems, improve them together and try to get into a new version.
> 
> @zeroskylian @cashleeboy @infinitepower18 @isaac-weisberg @lambda123254 @ZYHshao @18320537910

Thanks, I just simply checked that SnapKit does not use these APIs from https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api . I don’t know if there are other APIs. If so, please help add them.

**Comment by wlxo0401** [comment]
@robertjpayne 

A lot of time has passed since the last SnapKit update.

Do you have any plans regarding Privacy Manifest??

**Comment by robertjpayne** [comment]
But late, but it's landed in 5.7.0. Cannot support Cocoapods because it has an open PR for support for this but if you use the framework directly or via Swift PM it should be good.

Open a new issue if not thanks all!

**Comment by drewolbrich** [comment]
@robertjpayne Thank you for releasing 5.7.0. 😀

**Comment by hystericcore** [comment]
@robertjpayne Thanks for the update! 

I noticed that version 5.7.0 doesn't currently support cocoapods.

I've read the [Cocoapods PR](https://github.com/CocoaPods/CocoaPods/issues/10325) and seems we can include a privacy manifest with `resource_bundles`. Would it be possible for you to update podspec similarly to that? 

```
   s.resource_bundles = {'SnapKit' => ['Sources/PrivacyInfo.xcprivacy']}
```

**Comment by robertjpayne** [comment]
@hystericcore if you read further down the issue that isn't a workable solution since the resource bundle is part of *all* pods installed and thus you end up with conflicts.

Until Cocoapods provides an appropriate solution I wont really attempt to resolve it. For those that are using Cocoapods I'd recommend using custom build steps or something to integrate the privacy manifests required.

**Comment by robertjpayne** [comment]
My professional and personal opinion is that people should migrate away from Cocoapods as soon as reasonable to do so. Most dependencies can be integrated via Swift PM or in cases with more specific build requirements Carthage provides isolation at a per-dependency level.

I know there are some bigger projects (looking at you react-native) that will *only* work with Cocoapods. It'll be interesting to see how they resolve the privacy manifest issue before Spring 2024.

**Comment by mjburghard** [comment]
@robertjpayne I do agree with your opinion that people should migrate away from Cocoapods. The solution suggested by @hystericcore seems to work for other pods though. What's not working is using `s.resources`.
Using `s.resource_bundles` causes the generation of `SnapKit.bundle/PrivacyInfo.xcprivacy` inside `SnapKit.framework`.
I am happy to follow up with a PR based on my local testing.

**Comment by dcacenabes** [comment]
Hi there! I took the freedom of opening the PR adding resource_bundles. As pointed out by @mjburghard resource_bundles are safe to use since they do not cause name collisions.
https://github.com/SnapKit/SnapKit/pull/798

This is how Google is adding support for Privacy manifest to their dependencies. More details can be found [here](https://github.com/google/promises/pull/226#discussion_r1447871477)

**Comment by wlxo0401** [comment]
I discovered a new while testing. 

Until now, most of the libraries that have added PrivacyInfo have not been marked in PrivacyReport. 

However, when an item is added to the 'Privacy Nutrition Label Types', the library name is displayed in the PrivacyReport. 

Many libraries have updated PrivacyInfo without adding anything from 'Privacy Nutrition Label Types'.

Does anyone know about this? Is 'Privacy Nutrition Label Types' a must-have item? 

Or is it not necessary to display it in the privacy report?

Please feel free to leave opinion.

The 'PrivacyReport' I'm talking about can be downloaded as a PDF if you archive the app.

https://developer.apple.com/videos/play/wwdc2023/10060/
Please refer to 3:20.

1. Open your project in Xcode.

2. Choose Product > Archive. Xcode creates the archive and reveals it in the organizer.

3. Control-click the archive in the organizer and choose Generate Privacy Report.

(I used a translator.)
