### ISSUE TITLE
Can't download the latest (5.7.0) version with cocoapods

### ISSUE THREAD

**Issue by Gargo** [Masonry/Snap#797]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                iOS
 Platform Version        15+
 SnapKit Version         5.7.0
 Integration Method      cocoapods
 

### Issue Description

According to readme:

`pod 'SnapKit', '~> 5.7.0'`
but it doesn't work:
```
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "SnapKit":
  In Podfile:
    SnapKit (~> 5.7.0)

None of your spec sources contain a spec satisfying the dependency: `SnapKit (~> 5.7.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

In the same time when I delete the concrete version number it downloads 5.6.0 and it works

**Comment by mayios** [comment]
The same thing happens to me too.

pod 'SnapKit', :git => 'https://github.com/SnapKit/SnapKit.git'

As above, 5.7.0 was installed by importing it from the repository, but there is no privacyinfo file.

How can I solve this?

**Comment by wlxo0401** [comment]
> The same thing happens to me too.
> 
> pod 'SnapKit', :git => 'https://github.com/SnapKit/SnapKit.git'
> 
> As above, 5.7.0 was installed by importing it from the repository, but there is no privacyinfo file.
> 
> How can I solve this?

This issue seems to be that the 5.7.0 version itself is not installable. 

But it seems that you don't have Privacy Manifest even though 5.7.0 is installed. 

Shouldn't we look at it as a different issue?

**Comment by mayios** [comment]
> > The same thing happens to me too.
> > pod 'SnapKit', :git => 'https://github.com/SnapKit/SnapKit.git'
> > As above, 5.7.0 was installed by importing it from the repository, but there is no privacyinfo file.
> > How can I solve this?
> 
> This issue seems to be that the 5.7.0 version itself is not installable.
> 
> But it seems that you don't have Privacy Manifest even though 5.7.0 is installed.
> 
> Shouldn't we look at it as a different issue?

thank u, I know the two problems are different.

I just want to know how to solve two things.

**Comment by wlxo0401** [comment]
> > > The same thing happens to me too.
> > > pod 'SnapKit', :git => 'https://github.com/SnapKit/SnapKit.git'
> > > As above, 5.7.0 was installed by importing it from the repository, but there is no privacyinfo file.
> > > How can I solve this?
> > 
> > 
> > This issue seems to be that the 5.7.0 version itself is not installable.
> > But it seems that you don't have Privacy Manifest even though 5.7.0 is installed.
> > Shouldn't we look at it as a different issue?
> 
> thank u, I know the two problems are different.
> 
> I just want to know how to solve two things.

One of the best ways would be to create and manage issues separately. 

That way, it won't be forgotten..

**Comment by robertjpayne** [comment]
5.7.0 isn't available on Cocoapods because I've been waiting to see their official stance on the privacy manifests. I should probably just push it to trunk and then deal with the privacy manifest in another release.

**Comment by Gargo** [comment]
@robertjpayne 3 weeks passed. How much time does it usually takes?

**Comment by robertjpayne** [comment]
5.7.1 is now updated on Cocoapods.
