### ISSUE TITLE
My project supports iOS11

### ISSUE THREAD

**Issue by lxsvlog** [Masonry/Snap#799]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 11.0
 SnapKit Version         | 5.7.0
 Integration Method      | cocoapods
 

### Issue Description
The current Snapkit tags that contain privacy lists are supported starting from iOS12. What should iOS11 projects do?

**Comment by wlxo0401** [comment]
If Privacy Manifest is not supported in your library, there are people who say it can be solved by adding PrivacyInfo to your app. This is a possibility, and I'm not sure how Apple will react. [StackOverflow](https://stackoverflow.com/questions/77400419/necessity-of-privacy-manifest-for-third-party-sdk-in-app-review?noredirect=1#comment137346344_77400419)

However, since Apple mentioned SnapKit as a library that requires PrivacyManifest, it is doubtful that the above method will work. 

I also suspect that Apple is using this policy to reinvigorate the community and clean up neglected apps and libraries.

**Comment by lxsvlog** [comment]
> PrivacyInfo



> If Privacy Manifest is not supported in your library, there are people who say it can be solved by adding PrivacyInfo to your app. This is a possibility, and I'm not sure how Apple will react. [StackOverflow](https://stackoverflow.com/questions/77400419/necessity-of-privacy-manifest-for-third-party-sdk-in-app-review?noredirect=1#comment137346344_77400419)
> 
> However, since Apple mentioned SnapKit as a library that requires PrivacyManifest, it is doubtful that the above method will work.
> 
> I also suspect that Apple is using this policy to reinvigorate the community and clean up neglected apps and libraries.

I found that the latest version of snapkit, 5.7.0, is required to be supported starting from iOS12 system, and it has also been added to the privacy list starting from 5.7.0. However, it is obvious that the minimum supported iOS system for many developers may be very low, such as my project requirements. The system version is iOS11 or above, which means that my project cannot use the latest version of snapkit, nor can I add a privacy list according to Apple's privacy policy. If I want to have a privacy list, I need to fork snapkit and add it myself. Obviously this is not very suitable. I want to know why snapkit is suddenly supported from iOS12? What should developers like us who support iOS11 do? Are there any APIs that require iOS 12 or above to be used?

**Comment by lxsvlog** [comment]
> If Privacy Manifest is not supported in your library, there are people who say it can be solved by adding PrivacyInfo to your app. This is a possibility, and I'm not sure how Apple will react. [StackOverflow](https://stackoverflow.com/questions/77400419/necessity-of-privacy-manifest-for-third-party-sdk-in-app-review?noredirect=1#comment137346344_77400419)
> 
> However, since Apple mentioned SnapKit as a library that requires PrivacyManifest, it is doubtful that the above method will work.
> 
> I also suspect that Apple is using this policy to reinvigorate the community and clean up neglected apps and libraries.

According to Apple's policy, snapkit must have a Privacy Manifest, so even if there is one in my project, it cannot replace snapkit's Privacy Manifest.

**Comment by robertjpayne** [comment]
Hi you're free to fork the library and rename it to include it in unsupported OS versions thus bypassing the SDK requirements.

**Comment by Saikumar-Reddy** [comment]
> ### New Issue Checklist
> 🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫
> 
> * [x]  I have looked at the [Documentation](http://snapkit.io/docs)[x]  I have read the [F.A.Q.](http://snapkit.io/faq)[x]  I have filled out this issue template.
> 
> ### Issue Info
> Info	Value
> Platform	ios
> Platform Version	11.0
> SnapKit Version	5.7.0
> Integration Method	cocoapods
> ### Issue Description
> The current Snapkit tags that contain privacy lists are supported starting from iOS12. What should iOS11 projects do?

Did you find any solution?
