### ISSUE TITLE
SnapKit SDK Signature

### ISSUE THREAD

**Issue by Muesly** [Masonry/Snap#800]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | e.g. carthage/cocoapods/manually
 

### Issue Description

Thank you for adding an App Privacy Manifest file.  In addition Apple requires an SDK Signature file:

From https://developer.apple.com/support/third-party-SDK-requirements/:

> Signatures for SDKs
Now with signatures for SDKs, when you adopt a new version of a third-party SDK in your app, Xcode will validate that it was signed by the same developer, improving the integrity of your software supply chain.

Here is an example of one from Lottie SDK:
https://github.com/airbnb/lottie-ios/pull/2259

Would you be able to start adding this to the repo too for the current and future versions?

Many thanks!

**Comment by robertjpayne** [comment]
We don't provide SnapKit in binary format there for no signature is required.
