### ISSUE TITLE
Difference between offset and inset?

### ISSUE THREAD

**Issue by gerchicov-vg** [Masonry/Snap#806]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | any
 Platform Version        | any
 SnapKit Version         | any
 Integration Method      | any
 

### Issue Description

I have the following code chunks:
```
someView.snp.makeConstraings {
    $0.top.equalToSuperview().offset(16)
}
```

```
someView.snp.makeConstraings {
    $0.top.equalToSuperview().inset(16)
}
```

Is there any difference (except of +/- signs before number)?

**Comment by robertjpayne** [comment]
@gerchicov-vg offset's are always added to the constraint e.g. `top + <offset>` where as insets depend on the edge:

```
top + <inset>
bottom - <inset>
left + <inset>
right - <inset>
leading + <inset>
trailing - <inset>
```
