### ISSUE TITLE
Can YOu MAkE it SuPpoRt SwIfT 6????!!!

### ISSUE THREAD

**Issue by acincor** [Masonry/Snap#820]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | e.g. carthage/cocoapods/manually
 

### Issue Description

⚠️ Replace this with the description of your issue. ⚠️

**Comment by acincor** [comment]
My Target was supported Swift 6 language mode by myself, but I had used your project, So I cannot migrate it to Swift 6 all right!

**Comment by robertjpayne** [comment]
Closing this issue. It's not useful to construct issue titles with "meme" like titles like this.
